<?php

return [
    'categories' => [
        'Business or Brand' => [
            'Company',
            'Local Business',
            'Retail Company',
            'Clothing Store',
            'Restaurant',
            'Café',
            'Hotel',
            'Travel Agency',
            'Website',
            'App Page',
            'E-commerce Website',
        ],
        'Artist, Band or Public Figure' => [
            'Musician/Band',
            'Artist',
            'Actor/Director',
            'Author',
            'Blogger',
            'Chef',
            'Coach',
            'Comedian',
            'Dancer',
            'Entrepreneur',
            'Gamer',
            'Journalist',
            'Politician',
            'Public Figure',
            'Scientist',
            'Teacher',
        ],
        'Entertainment' => [
            'Entertainment Website',
            'TV Show',
            'Movie',
            'Book',
            'Podcast',
            'Video Creator',
            'Radio Station',
            'Sports Team',
            'Gaming Video Creator',
        ],
        'Community' => [
            'Community',
            'Interest Group',
            'Support Group',
            'Fan Page',
            'Cause',
            'Club',
        ],
        'Cause or Institution' => [
            'Nonprofit Organization',
            'Charity Organization',
            'School',
            'College/University',
            'Church/Religious Organization',
            'Hospital',
            'Government Organization',
            'Media/News Company',
        ],
    ],
];
